# Config file for CelebA dataset (200k)

output_dir: '/kaggle/working/water'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: '/kaggle/input/raw50/04_water'
  folder: False
  resolution: 128
sched:
  # epochs: [2,4,4,4,4,8]
  epochs: [8,16,16,64,512,2000]
