output_dir: '/data/hzh/checkpoints/StyleGAN.pytorch/ckp_celeba_2'
structure: 'linear'
device_id: ('2')
dataset:
  img_dir: '/home/hzh/data/img_align_celeba'
  folder: False
  resolution: 32
sched:
  epochs: [1, 1, 1, 1, 1, 1, 32, 64, 64]