# Config file for CelebA dataset (200k)

output_dir: '/kaggle/working/dig'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: '/kaggle/input/raw50/02_dig'
  folder: False
  resolution: 128
sched:
  epochs: [2,4,4,4,4]
